### ISSUE TITLE
env.reset error!

### ISSUE THREAD

**Issue by yigeNNU** [lascavana/rl2branch#4]
Hi! @lascavana, when I run to execute this command **"python 02_get_instance_solutions.py indset -j 8",**  it reports the following error, is there a problem with my ecole installation?

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zhangyige/rl2branch-master/02_get_instance_solutions.py", line 50, in solve_instance
    env.reset(str(instance))
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/site-packages/ecole/environment.py", line 134, in reset
    raise e
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/site-packages/ecole/environment.py", line 124, in reset
    reward_offset = self.reward_function.extract(self.model, done)
  File "/home/zhangyige/rl2branch-master/02_get_instance_solutions.py", line 25, in extract
    pyscipopt_model = model.as_pyscipopt()
  File "src/pyscipopt/scip.pyx", line 992, in pyscipopt.scip.Model.from_ptr
TypeError: an integer is required
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zhangyige/rl2branch-master/02_get_instance_solutions.py", line 50, in solve_instance
    env.reset(str(instance))
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/site-packages/ecole/environment.py", line 134, in reset
    raise e
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/site-packages/ecole/environment.py", line 124, in reset
    reward_offset = self.reward_function.extract(self.model, done)
  File "/home/zhangyige/rl2branch-master/02_get_instance_solutions.py", line 25, in extract
    pyscipopt_model = model.as_pyscipopt()
  File "src/pyscipopt/scip.pyx", line 992, in pyscipopt.scip.Model.from_ptr
TypeError: an integer is required
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zhangyige/rl2branch-master/02_get_instance_solutions.py", line 50, in solve_instance
    env.reset(str(instance))
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/site-packages/ecole/environment.py", line 134, in reset
    raise e
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/site-packages/ecole/environment.py", line 124, in reset
    reward_offset = self.reward_function.extract(self.model, done)
  File "/home/zhangyige/rl2branch-master/02_get_instance_solutions.py", line 25, in extract
    pyscipopt_model = model.as_pyscipopt()
  File "src/pyscipopt/scip.pyx", line 992, in pyscipopt.scip.Model.from_ptr
TypeError: an integer is required
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zhangyige/rl2branch-master/02_get_instance_solutions.py", line 50, in solve_instance
Exception in thread Thread-5:
Traceback (most recent call last):
    env.reset(str(instance))
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/site-packages/ecole/environment.py", line 134, in reset
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    raise e
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/site-packages/ecole/environment.py", line 124, in reset
    self.run()
    reward_offset = self.reward_function.extract(self.model, done)
  File "/home/zhangyige/rl2branch-master/02_get_instance_solutions.py", line 25, in extract
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/threading.py", line 910, in run
    pyscipopt_model = model.as_pyscipopt()
  File "src/pyscipopt/scip.pyx", line 992, in pyscipopt.scip.Model.from_ptr
    self._target(*self._args, **self._kwargs)
TypeError: an integer is required
  File "/home/zhangyige/rl2branch-master/02_get_instance_solutions.py", line 50, in solve_instance
Exception in thread Thread-6:
    env.reset(str(instance))
Traceback (most recent call last):
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/site-packages/ecole/environment.py", line 134, in reset
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    raise e
    self.run()
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/site-packages/ecole/environment.py", line 124, in reset
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zhangyige/rl2branch-master/02_get_instance_solutions.py", line 50, in solve_instance
    env.reset(str(instance))
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/site-packages/ecole/environment.py", line 134, in reset
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/threading.py", line 973, in _bootstrap_inner
Exception in thread Thread-3:
    raise e
Traceback (most recent call last):
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/site-packages/ecole/environment.py", line 124, in reset
    reward_offset = self.reward_function.extract(self.model, done)
    self.run()
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/threading.py", line 973, in _bootstrap_inner
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/threading.py", line 910, in run
  File "/home/zhangyige/rl2branch-master/02_get_instance_solutions.py", line 25, in extract
    reward_offset = self.reward_function.extract(self.model, done)
    self._target(*self._args, **self._kwargs)
  File "/home/zhangyige/rl2branch-master/02_get_instance_solutions.py", line 25, in extract
    self.run()
    pyscipopt_model = model.as_pyscipopt()
  File "src/pyscipopt/scip.pyx", line 992, in pyscipopt.scip.Model.from_ptr
    pyscipopt_model = model.as_pyscipopt()
  File "/home/zhangyige/rl2branch-master/02_get_instance_solutions.py", line 50, in solve_instance
  File "src/pyscipopt/scip.pyx", line 992, in pyscipopt.scip.Model.from_ptr
TypeError: an integer is required
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/threading.py", line 910, in run
    env.reset(str(instance))
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/site-packages/ecole/environment.py", line 134, in reset
    raise e
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/site-packages/ecole/environment.py", line 124, in reset
    reward_offset = self.reward_function.extract(self.model, done)
  File "/home/zhangyige/rl2branch-master/02_get_instance_solutions.py", line 25, in extract
    self._target(*self._args, **self._kwargs)
  File "/home/zhangyige/rl2branch-master/02_get_instance_solutions.py", line 50, in solve_instance
    pyscipopt_model = model.as_pyscipopt()
  File "src/pyscipopt/scip.pyx", line 992, in pyscipopt.scip.Model.from_ptr
    env.reset(str(instance))
TypeError: an integer is required
TypeError: an integer is required
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/site-packages/ecole/environment.py", line 134, in reset
    raise e
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/site-packages/ecole/environment.py", line 124, in reset
    reward_offset = self.reward_function.extract(self.model, done)
  File "/home/zhangyige/rl2branch-master/02_get_instance_solutions.py", line 25, in extract
    pyscipopt_model = model.as_pyscipopt()
  File "src/pyscipopt/scip.pyx", line 992, in pyscipopt.scip.Model.from_ptr
TypeError: an integer is required
^CTraceback (most recent call last):
  File "/home/zhangyige/rl2branch-master/02_get_instance_solutions.py", line 115, in <module>
    answer = answers_queue.get()
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/queue.py", line 171, in get
    self.not_empty.wait()
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()
KeyboardInterrupt

**Comment by yigeNNU** [comment]
After checking, I think there should be a problem with the customized reward function, here are the changes I made, but it still reports an error.

class OptimalSol:

    def __init__(self):
        pass

    def before_reset(self, model: ecole.scip.Model):
        pass

    def extract(self, model: ecole.scip.Model, done=False):

        import pyscipopt
        # ecole_model becomes pointer owner
        ecole_model = model.from_pyscipopt(pyscipopt.Model())
        if done:
            reward = ecole_model.getObjVal(original=True)
            print('reward:', reward)
        else:
            reward = None

        return reward

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zhangyige/rl2branch-master/02_get_instance_solutions.py", line 58, in solve_instance
    env.reset(instance)
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/site-packages/ecole/environment.py", line 134, in reset
    raise e
  File "/home/zhangyige/.conda/envs/rl2mdp/lib/python3.9/site-packages/ecole/environment.py", line 124, in reset
    reward_offset = self.reward_function.extract(self.model, done)
  File "/home/zhangyige/rl2branch-master/02_get_instance_solutions.py", line 30, in extract
    ecole_model = model.from_pyscipopt(pyscipopt.Model())
TypeError: Object of type 'int' is not an instance of 'capsule'

**Comment by lascavana** [comment]
Hi! Could you check your Ecole installation? You need [this](https://github.com/lascavana/ecole) version. I have updated the installation instructions to be more clear. Thanks!
